// frontend/angular/src/app/pages/transactions.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { AuthService } from '../core/auth.service';
import { FavoritePayee, StatementEntryResponse, TransactionResponse } from '../core/models';
import { formatBRL, formatDateTime, formatDateTimeShort, formatSigned } from '../core/format';
import { FormErrorComponent } from '../shared/form-error.component';

@Component({
  selector: 'fh-transactions',
  imports: [FormsModule, FormErrorComponent],
  template: `
    <div>
      <div style="display:flex; flex-wrap:wrap; justify-content:space-between; gap:1rem; align-items:flex-end;">
        <div>
          <p class="kicker">Conta</p>
          <h1 class="display" style="font-size: 2.25rem; margin: 0.5rem 0 0;">Extrato</h1>
          <p class="muted">Movimentações com saldo após cada lançamento.</p>
        </div>
        <div class="row">
          <button class="btn btn-ghost" type="button" [disabled]="downloadingStatement() || !entries().length" (click)="downloadStatement()">
            {{ downloadingStatement() ? 'Gerando PDF…' : 'Exportar extrato PDF' }}
          </button>
          <button class="btn btn-ghost" type="button" (click)="load()">Atualizar</button>
        </div>
      </div>

      <section class="card" style="margin: 1.5rem 0; display:flex; justify-content:space-between; align-items:baseline;">
        <div>
          <p class="kicker">Saldo atual</p>
          <p class="money display" style="font-size:1.5rem; margin:0.25rem 0 0;">
            {{ currentBalance() == null ? '—' : formatBRL(currentBalance()!) }}
          </p>
        </div>
        <p class="mono muted" style="font-size:0.7rem;">{{ sessionDocument() }}</p>
      </section>

      <fh-form-error [error]="error()" (dismiss)="error.set(null)" />

      @if (loading() && !entries().length) {
        <p class="muted">Carregando extrato…</p>
      } @else if (!entries().length) {
        <p class="card" style="text-align:center; padding:2rem;">Nenhuma movimentação ainda. Faça uma transferência para ver o extrato aqui.</p>
      } @else {
        <div class="grid-tx">
          <div class="card" style="padding:0; overflow:hidden;">
            <div class="tx-row tx-head">
              <span>Movimentação</span><span style="text-align:right;">Valor</span>
              <span style="text-align:right;">Saldo</span><span style="text-align:right;">Quando</span>
            </div>
            @for (entry of entries(); track entry.transaction.id) {
              <button type="button" class="tx-row" [class.active]="entry.transaction.id === selectedId()" (click)="selectedId.set(entry.transaction.id)">
                <div>
                  <p style="margin:0; font-size:0.875rem;">{{ movementLabel(entry.transaction) }}</p>
                  <p class="muted" style="margin:0.2rem 0 0; font-size:0.7rem;">{{ entry.transaction.type }} · {{ entry.transaction.status }}</p>
                </div>
                <p style="margin:0; text-align:right;" [style.color]="entry.signedAmount < 0 ? '#fecaca' : '#a7f3d0'">{{ formatSigned(entry.signedAmount) }}</p>
                <p class="mono" style="margin:0; text-align:right; font-size:0.875rem;">{{ entry.balanceAfter == null ? '—' : formatBRL(entry.balanceAfter) }}</p>
                <p class="muted" style="margin:0; text-align:right; font-size:0.7rem;">{{ formatDateTimeShort(entry.transaction.createdAt) }}</p>
              </button>
            }
          </div>
          @if (selected(); as tx) {
            <div class="card">
              <p class="kicker">{{ tx.status }}</p>
              <p style="margin:0.4rem 0 0;">{{ formatSigned(selectedEntry()!.signedAmount) }}</p>
              <p class="muted">Pagador: {{ tx.payerName }} · {{ tx.payerDocument }}</p>
              <p class="muted">Recebedor: {{ tx.payeeName }} · {{ tx.payeeDocument }}</p>
              <p class="muted">{{ formatDateTime(tx.createdAt) }}</p>
              <p class="mono muted" style="font-size:0.7rem; word-break:break-all;">{{ tx.id }}</p>
              <div style="margin-top:1rem; display:grid; gap:0.5rem;">
                <button class="btn btn-ghost" type="button" (click)="downloadReceipt()" [disabled]="downloadingReceipt()">
                  {{ downloadingReceipt() ? 'Gerando PDF…' : 'Exportar comprovante PDF' }}
                </button>
                @if (canFavorite()) {
                  <button class="btn btn-ghost" type="button" (click)="toggleFavorite()">
                    {{ counterpartyFavorited() ? 'Remover dos favoritos' : 'Favoritar contraparte' }}
                  </button>
                }
              </div>
              @if (canReverse()) {
                <label class="field" style="margin-top:1rem;">
                  <span class="label">Motivo do estorno</span>
                  <input class="input" [(ngModel)]="reason" name="reason" />
                </label>
                <button class="btn btn-ghost" type="button" (click)="onReverse()" [disabled]="reversing()">
                  {{ reversing() ? 'Estornando…' : 'Estornar transferência' }}
                </button>
              }
            </div>
          }
        </div>
      }
    </div>
  `,
})
export class TransactionsComponent implements OnInit {
  private readonly api = inject(ApiService);
  private readonly auth = inject(AuthService);

  entries = signal<StatementEntryResponse[]>([]);
  currentBalance = signal<number | null>(null);
  favorites = signal<FavoritePayee[]>([]);
  selectedId = signal<string | null>(null);
  reason = 'Estorno solicitado pelo usuário';
  error = signal<unknown>(null);
  loading = signal(true);
  reversing = signal(false);
  downloadingReceipt = signal(false);
  downloadingStatement = signal(false);

  formatBRL = formatBRL;
  formatSigned = formatSigned;
  formatDateTime = formatDateTime;
  formatDateTimeShort = formatDateTimeShort;

  ngOnInit() {
    void this.load();
  }

  sessionDocument() {
    return this.auth.session()?.document ?? '';
  }

  selectedEntry() {
    return this.entries().find((e) => e.transaction.id === this.selectedId()) ?? null;
  }

  selected() {
    return this.selectedEntry()?.transaction ?? null;
  }

  canReverse() {
    const tx = this.selected();
    return tx?.type === 'TRANSFER' && tx.status === 'COMPLETED' && tx.payerDocument === this.sessionDocument();
  }

  counterparty() {
    const tx = this.selected();
    const doc = this.sessionDocument();
    if (!tx) return null;
    return tx.payerDocument === doc
      ? { document: tx.payeeDocument, name: tx.payeeName }
      : { document: tx.payerDocument, name: tx.payerName };
  }

  canFavorite() {
    const cp = this.counterparty();
    return Boolean(cp?.document) && cp?.document !== this.sessionDocument();
  }

  counterpartyFavorited() {
    const cp = this.counterparty();
    return Boolean(cp?.document && this.favorites().some((f) => f.document === cp.document));
  }

  movementLabel(tx: TransactionResponse) {
    const outbound = tx.payerDocument === this.sessionDocument();
    if (tx.type === 'REVERSAL') {
      return outbound ? `Estorno para ${tx.payeeName ?? '—'}` : `Estorno de ${tx.payerName ?? '—'}`;
    }
    return outbound ? `Transferência para ${tx.payeeName ?? '—'}` : `Transferência de ${tx.payerName ?? '—'}`;
  }

  async load() {
    const session = this.auth.session();
    if (!session) return;
    this.loading.set(true);
    this.error.set(null);
    try {
      const statement = await this.api.listTransactions(session.document);
      this.entries.set(statement.entries);
      this.currentBalance.set(statement.currentBalance);
      this.selectedId.set(statement.entries[0]?.transaction.id ?? null);
      try {
        const fav = await this.api.listFavorites(session.document);
        this.favorites.set(fav.favorites);
      } catch {
        this.favorites.set(this.api.localFavorites(session.document));
      }
    } catch (err) {
      this.error.set(err);
      this.entries.set([]);
    } finally {
      this.loading.set(false);
    }
  }

  async onReverse() {
    const tx = this.selected();
    if (!tx) return;
    this.reversing.set(true);
    try {
      const reversal = await this.api.reverse({ transactionId: tx.id, reason: this.reason });
      await this.load();
      this.selectedId.set(reversal.id);
    } catch (err) {
      this.error.set(err);
    } finally {
      this.reversing.set(false);
    }
  }

  async toggleFavorite() {
    const session = this.auth.session();
    const cp = this.counterparty();
    if (!session || !cp?.document) return;
    try {
      const res = this.counterpartyFavorited()
        ? await this.api.removeFavorite(session.document, cp.document)
        : await this.api.addFavorite(session.document, { document: cp.document, name: cp.name ?? cp.document });
      this.favorites.set(res.favorites);
    } catch (err) {
      this.error.set(err);
    }
  }

  async downloadReceipt() {
    const tx = this.selected();
    if (!tx) return;
    this.downloadingReceipt.set(true);
    try {
      const blob = await this.api.downloadReceipt(tx.id);
      this.api.triggerDownload(blob, `comprovante-${tx.id}.pdf`);
    } catch (err) {
      this.error.set(err);
    } finally {
      this.downloadingReceipt.set(false);
    }
  }

  async downloadStatement() {
    const session = this.auth.session();
    if (!session) return;
    this.downloadingStatement.set(true);
    try {
      const blob = await this.api.downloadStatement(session.document);
      this.api.triggerDownload(blob, `extrato-${session.document}.pdf`);
    } catch (err) {
      this.error.set(err);
    } finally {
      this.downloadingStatement.set(false);
    }
  }
}

// frontend/next/src/app/app/transactions/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import {
  downloadReceipt,
  downloadStatementPdf,
  listUserTransactions,
  reverseTransaction,
  triggerBlobDownload,
  type StatementEntryResponse,
  type TransactionResponse,
} from "@/lib/api";
import {
  isFavorite,
  listFavorites,
  toggleFavorite,
  type FavoritePayee,
} from "@/lib/favorites";
import { formatBRL } from "@/lib/money";
import { formatDateTime, formatDateTimeShort } from "@/lib/datetime";
import {
  FormError,
  Field,
  inputClass,
  buttonGhostClass,
} from "@/components/ui";

export default function TransactionsPage() {
  const { session } = useAuth();
  const [entries, setEntries] = useState<StatementEntryResponse[]>([]);
  const [currentBalance, setCurrentBalance] = useState<number | null>(null);
  const [favorites, setFavorites] = useState<FavoritePayee[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [reason, setReason] = useState("Estorno solicitado pelo usuário");
  const [error, setError] = useState<unknown>(null);
  const [loading, setLoading] = useState(true);
  const [reversing, setReversing] = useState(false);
  const [downloadingReceipt, setDownloadingReceipt] = useState(false);
  const [downloadingStatement, setDownloadingStatement] = useState(false);

  const load = useCallback(async () => {
    if (!session) return;
    setLoading(true);
    setError(null);
    try {
      const statement = await listUserTransactions(session.document, session.token, 50);
      setEntries(statement.entries);
      setCurrentBalance(statement.currentBalance);
      setFavorites(listFavorites(session.document));
      setSelectedId((current) => {
        if (current && statement.entries.some((e) => e.transaction.id === current)) {
          return current;
        }
        return statement.entries[0]?.transaction.id ?? null;
      });
    } catch (err) {
      setError(err);
      setEntries([]);
      setCurrentBalance(null);
    } finally {
      setLoading(false);
    }
  }, [session]);

  useEffect(() => {
    void load();
  }, [load]);

  const selectedEntry = entries.find((e) => e.transaction.id === selectedId) ?? null;
  const selected = selectedEntry?.transaction ?? null;

  const canReverse =
    selected?.type === "TRANSFER" &&
    selected?.status === "COMPLETED" &&
    selected.payerDocument === session?.document;

  const counterparty =
    selected && session
      ? selected.payerDocument === session.document
        ? {
            document: selected.payeeDocument,
            name: selected.payeeName,
          }
        : {
            document: selected.payerDocument,
            name: selected.payerName,
          }
      : null;

  const canFavorite =
    Boolean(session) &&
    Boolean(counterparty?.document) &&
    counterparty?.document !== session?.document;

  const counterpartyFavorited =
    session && counterparty?.document
      ? isFavorite(session.document, counterparty.document)
      : false;

  async function onReverse() {
    if (!session || !selected) return;
    setError(null);
    setReversing(true);
    try {
      const reversal = await reverseTransaction(
        { transactionId: selected.id, reason },
        session.token
      );
      await load();
      setSelectedId(reversal.id);
    } catch (err) {
      setError(err);
    } finally {
      setReversing(false);
    }
  }

  function onToggleFavorite() {
    if (!session || !counterparty?.document) return;
    const next = toggleFavorite(session.document, {
      document: counterparty.document,
      name: counterparty.name ?? counterparty.document,
    });
    setFavorites(next);
  }

  async function onDownloadReceipt() {
    if (!session || !selected) return;
    setError(null);
    setDownloadingReceipt(true);
    try {
      const blob = await downloadReceipt(selected.id, session.token);
      triggerBlobDownload(blob, `comprovante-${selected.id}.pdf`);
    } catch (err) {
      setError(err);
    } finally {
      setDownloadingReceipt(false);
    }
  }

  async function onDownloadStatement() {
    if (!session) return;
    setError(null);
    setDownloadingStatement(true);
    try {
      const blob = await downloadStatementPdf(session.document, session.token, 50);
      triggerBlobDownload(blob, `extrato-${session.document}.pdf`);
    } catch (err) {
      setError(err);
    } finally {
      setDownloadingStatement(false);
    }
  }

  return (
    <div className="space-y-8">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-xs uppercase tracking-[0.16em] text-white/45">Conta</p>
          <h1 className="mt-2 font-[family-name:var(--font-display)] text-4xl">
            Extrato
          </h1>
          <p className="mt-2 text-sm text-white/55">
            Movimentações com saldo após cada lançamento.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => void onDownloadStatement()}
            disabled={downloadingStatement || entries.length === 0}
            className={buttonGhostClass}
          >
            {downloadingStatement ? "Gerando PDF…" : "Exportar extrato PDF"}
          </button>
          <button type="button" onClick={() => void load()} className={buttonGhostClass}>
            Atualizar
          </button>
        </div>
      </div>

      <section className="flex flex-wrap items-baseline justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3">
        <div>
          <p className="text-[10px] uppercase tracking-[0.14em] text-white/45">Saldo atual</p>
          <p className="mt-1 font-[family-name:var(--font-display)] text-xl text-[var(--amber)] sm:text-2xl">
            {currentBalance == null ? "—" : formatBRL(currentBalance)}
          </p>
        </div>
        {session?.document && (
          <p className="font-mono text-[11px] text-white/35">{session.document}</p>
        )}
      </section>

      <FormError error={error} onDismiss={() => setError(null)} />

      {loading && entries.length === 0 ? (
        <p className="text-white/50">Carregando extrato…</p>
      ) : entries.length === 0 ? (
        <p className="rounded-xl border border-white/10 bg-white/[0.03] px-5 py-8 text-center text-white/55">
          Nenhuma movimentação ainda. Faça uma transferência para ver o extrato aqui.
        </p>
      ) : (
        <div className="grid gap-6 lg:grid-cols-[1.25fr_0.75fr]">
          <div className="overflow-hidden rounded-xl border border-white/10">
            <div className="grid grid-cols-[1.2fr_0.9fr_0.9fr_0.9fr] gap-2 border-b border-white/10 bg-white/[0.04] px-4 py-3 text-[10px] uppercase tracking-[0.12em] text-white/40 sm:grid-cols-[1.4fr_1fr_1fr_1fr]">
              <span>Movimentação</span>
              <span className="text-right">Valor</span>
              <span className="text-right">Saldo</span>
              <span className="hidden text-right sm:block">Quando</span>
            </div>
            <ul>
              {entries.map((entry) => {
                const tx = entry.transaction;
                const active = tx.id === selectedId;
                return (
                  <li key={tx.id} className="border-b border-white/5 last:border-b-0">
                    <button
                      type="button"
                      onClick={() => setSelectedId(tx.id)}
                      className={`grid w-full grid-cols-[1.2fr_0.9fr_0.9fr_0.9fr] gap-2 px-4 py-3.5 text-left transition sm:grid-cols-[1.4fr_1fr_1fr_1fr] ${
                        active
                          ? "bg-[var(--amber)]/10"
                          : "hover:bg-white/[0.04]"
                      }`}
                    >
                      <div className="min-w-0">
                        <p className="truncate text-sm text-[var(--foam)]">
                          {movementLabel(tx, session?.document)}
                        </p>
                        <p className="mt-0.5 text-[11px] text-white/40">
                          {tx.type} · {tx.status}
                        </p>
                      </div>
                      <p
                        className={`text-right text-sm font-medium ${
                          entry.signedAmount < 0
                            ? "text-red-200"
                            : entry.signedAmount > 0
                              ? "text-emerald-200"
                              : "text-white/70"
                        }`}
                      >
                        {formatSigned(entry.signedAmount)}
                      </p>
                      <p className="text-right font-mono text-sm text-white/75">
                        {entry.balanceAfter == null ? "—" : formatBRL(entry.balanceAfter)}
                      </p>
                      <p className="hidden text-right text-[11px] text-white/40 sm:block">
                        {formatDateTimeShort(tx.createdAt)}
                      </p>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>

          {selected && selectedEntry && (
            <div className="h-fit space-y-4 rounded-xl border border-white/10 bg-white/[0.03] p-5">
              <dl className="grid gap-3 text-sm">
                <Row label="Status" value={selected.status} highlight />
                <Row label="Tipo" value={selected.type} />
                <Row label="Valor" value={formatSigned(selectedEntry.signedAmount)} />
                <Row
                  label="Saldo após"
                  value={
                    selectedEntry.balanceAfter == null
                      ? "—"
                      : formatBRL(selectedEntry.balanceAfter)
                  }
                />
                <Party
                  label="Pagador"
                  document={selected.payerDocument}
                  name={selected.payerName}
                />
                <Party
                  label="Recebedor"
                  document={selected.payeeDocument}
                  name={selected.payeeName}
                />
                <Row
                  label="Criada em"
                  value={formatDateTime(selected.createdAt)}
                />
                {selected.failureReason && (
                  <Row label="Falha" value={selected.failureReason} />
                )}
                <Row label="ID" value={selected.id} mono />
              </dl>

              <div className="space-y-3 border-t border-white/10 pt-4">
                <button
                  type="button"
                  onClick={() => void onDownloadReceipt()}
                  disabled={downloadingReceipt}
                  className={buttonGhostClass}
                >
                  {downloadingReceipt ? "Gerando PDF…" : "Exportar comprovante PDF"}
                </button>

                {canFavorite && (
                  <>
                    <button
                      type="button"
                      onClick={onToggleFavorite}
                      className={buttonGhostClass}
                    >
                      {counterpartyFavorited
                        ? "Remover dos favoritos"
                        : `Favoritar ${counterparty?.name ?? "CPF/CNPJ"}`}
                    </button>
                    {favorites.length > 0 && (
                      <p className="text-xs text-white/40">
                        {favorites.length} favorito{favorites.length > 1 ? "s" : ""} salvos neste
                        navegador.
                      </p>
                    )}
                  </>
                )}
              </div>

              {canReverse && (
                <div className="space-y-3 border-t border-white/10 pt-4">
                  <Field label="Motivo do estorno">
                    <input
                      className={inputClass}
                      value={reason}
                      onChange={(e) => setReason(e.target.value)}
                    />
                  </Field>
                  <button
                    type="button"
                    onClick={() => void onReverse()}
                    disabled={reversing}
                    className={buttonGhostClass}
                  >
                    {reversing ? "Estornando…" : "Estornar transferência"}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function formatSigned(value: number) {
  const absolute = formatBRL(Math.abs(value));
  if (value > 0) return `+ ${absolute}`;
  if (value < 0) return `− ${absolute}`;
  return absolute;
}

function movementLabel(tx: TransactionResponse, viewerDocument?: string) {
  const outbound = tx.payerDocument === viewerDocument;
  if (tx.type === "REVERSAL") {
    return outbound
      ? `Estorno para ${tx.payeeName ?? tx.payeeDocument ?? "—"}`
      : `Estorno de ${tx.payerName ?? tx.payerDocument ?? "—"}`;
  }
  return outbound
    ? `Transferência para ${tx.payeeName ?? tx.payeeDocument ?? "—"}`
    : `Transferência de ${tx.payerName ?? tx.payerDocument ?? "—"}`;
}

function Party({
  label,
  document,
  name,
}: {
  label: string;
  document: string | null;
  name: string | null;
}) {
  return (
    <div>
      <dt className="text-white/40">{label}</dt>
      <dd className="mt-1">
        <p className="font-mono text-sm text-[var(--foam)]">
          {document ?? "—"}
        </p>
        <p className="mt-0.5 text-sm text-white/65">{name ?? "—"}</p>
      </dd>
    </div>
  );
}

function Row({
  label,
  value,
  mono,
  highlight,
}: {
  label: string;
  value: string;
  mono?: boolean;
  highlight?: boolean;
}) {
  return (
    <div>
      <dt className="text-white/40">{label}</dt>
      <dd
        className={`mt-1 break-all ${mono ? "font-mono text-xs" : ""} ${
          highlight ? "text-[var(--amber)]" : "text-[var(--foam)]"
        }`}
      >
        {value}
      </dd>
    </div>
  );
}
