// frontend/angular/src/app/pages/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { AuthService } from '../core/auth.service';
import { ApiClientError } from '../core/models';
import { onlyDigits, parseBRLInput } from '../core/format';
import { FormErrorComponent } from '../shared/form-error.component';
import { MoneyInputComponent } from '../shared/money-input.component';

@Component({
  selector: 'fh-register',
  imports: [FormsModule, RouterLink, FormErrorComponent, MoneyInputComponent],
  template: `
    <div class="page">
      <div class="bg-glow"></div>
      <div class="auth-wrap">
        <a routerLink="/" class="display" style="font-size: 1.5rem; margin-bottom: 2.5rem;">Financial Hub</a>
        <h1 class="display" style="font-size: 2.25rem; margin: 0;">Criar conta</h1>
        <p class="muted">Cadastro com saldo inicial. CPF (11 dígitos) ou CNPJ (14 dígitos).</p>
        <form (ngSubmit)="onSubmit()" novalidate style="margin-top: 2rem;">
          <label class="field">
            <span class="label">Nome</span>
            <input class="input" [class.error]="!!fieldErrors()['name']" [(ngModel)]="name" name="name" required />
            @if (fieldErrors()['name']) { <p class="field-error">{{ fieldErrors()['name'] }}</p> }
          </label>
          <label class="field">
            <span class="label">E-mail</span>
            <input class="input" type="email" [class.error]="!!fieldErrors()['email']" [(ngModel)]="email" name="email" required />
            @if (fieldErrors()['email']) { <p class="field-error">{{ fieldErrors()['email'] }}</p> }
          </label>
          <label class="field">
            <span class="label">CPF / CNPJ</span>
            <input class="input" [class.error]="!!fieldErrors()['document']" [(ngModel)]="document" name="document" required inputmode="numeric" maxlength="18" />
            @if (fieldErrors()['document']) { <p class="field-error">{{ fieldErrors()['document'] }}</p> }
          </label>
          <label class="field">
            <span class="label">Senha</span>
            <input class="input" type="password" [class.error]="!!fieldErrors()['password']" [(ngModel)]="password" name="password" required minlength="6" />
            @if (fieldErrors()['password']) { <p class="field-error">{{ fieldErrors()['password'] }}</p> }
          </label>
          <label class="field">
            <span class="label">Saldo inicial</span>
            <fh-money-input [value]="balanceMasked" [error]="!!fieldErrors()['initialBalance']" (valueChange)="onMoney($event)" />
            @if (fieldErrors()['initialBalance']) { <p class="field-error">{{ fieldErrors()['initialBalance'] }}</p> }
          </label>
          <fh-form-error [error]="error()" (dismiss)="error.set(null)" />
          <div class="row">
            <button class="btn btn-primary" type="submit" [disabled]="loading()">{{ loading() ? 'Criando…' : 'Criar conta' }}</button>
            <a routerLink="/login" class="btn btn-ghost">Já tenho conta</a>
          </div>
        </form>
      </div>
    </div>
  `,
})
export class RegisterComponent {
  private readonly api = inject(ApiService);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  name = '';
  email = '';
  document = '';
  password = '';
  balanceMasked = '1.000,00';
  balanceValue: number | null = 1000;
  error = signal<unknown>(null);
  fieldErrors = signal<Record<string, string>>({});
  loading = signal(false);

  onMoney(event: { masked: string; numeric: number | null }) {
    this.balanceMasked = event.masked;
    this.balanceValue = event.numeric;
  }

  async onSubmit() {
    const local: Record<string, string> = {};
    if (this.name.trim().length < 2) local['name'] = 'Nome deve ter pelo menos 2 caracteres';
    if (!this.email.includes('@')) local['email'] = 'E-mail inválido';
    const digits = onlyDigits(this.document);
    if (digits.length !== 11 && digits.length !== 14) {
      local['document'] = 'CPF deve ter 11 dígitos ou CNPJ 14 dígitos';
    }
    if (this.password.length < 6) local['password'] = 'Senha deve ter pelo menos 6 caracteres';
    const balance = this.balanceValue ?? parseBRLInput(this.balanceMasked);
    if (balance == null || balance < 0) local['initialBalance'] = 'Saldo inicial não pode ser negativo';
    this.fieldErrors.set(local);
    if (Object.keys(local).length) {
      this.error.set(new ApiClientError(400, { code: 'VALIDATION_ERROR', message: 'Um ou mais campos são inválidos', fields: local }));
      return;
    }
    this.loading.set(true);
    this.error.set(null);
    try {
      await this.api.createUser({
        name: this.name.trim(),
        email: this.email.trim(),
        document: digits,
        password: this.password,
        initialBalance: balance as number,
      });
      await this.auth.login(digits, this.password);
      await this.router.navigateByUrl('/app');
    } catch (err) {
      this.error.set(err);
      if (err instanceof ApiClientError) this.fieldErrors.set(err.fields);
    } finally {
      this.loading.set(false);
    }
  }
}

// frontend/next/src/app/register/page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { ApiClientError, createUser } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { MoneyInput } from "@/components/money-input";
import { parseBRLInput } from "@/lib/money";
import {
  FormError,
  Field,
  inputClass,
  inputErrorClass,
  buttonPrimaryClass,
  buttonGhostClass,
} from "@/components/ui";

function onlyDigits(value: string) {
  return value.replace(/\D/g, "");
}

function validateDocument(raw: string): string | undefined {
  const digits = onlyDigits(raw);
  if (!digits) return "CPF/CNPJ é obrigatório";
  if (digits.length !== 11 && digits.length !== 14) {
    return "CPF deve ter 11 dígitos ou CNPJ 14 dígitos";
  }
  return undefined;
}

export default function RegisterPage() {
  const { login } = useAuth();
  const router = useRouter();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [document, setDocument] = useState("");
  const [password, setPassword] = useState("");
  const [balanceMasked, setBalanceMasked] = useState("1.000,00");
  const [balanceValue, setBalanceValue] = useState<number | null>(1000);
  const [error, setError] = useState<unknown>(null);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);

  function validateLocal(): Record<string, string> {
    const next: Record<string, string> = {};
    if (name.trim().length < 2) next.name = "Nome deve ter pelo menos 2 caracteres";
    if (!email.includes("@")) next.email = "E-mail inválido";
    const docError = validateDocument(document);
    if (docError) next.document = docError;
    if (password.length < 6) next.password = "Senha deve ter pelo menos 6 caracteres";
    const balance = balanceValue ?? parseBRLInput(balanceMasked);
    if (balance == null || balance < 0) {
      next.initialBalance = "Saldo inicial não pode ser negativo";
    }
    return next;
  }

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    const localErrors = validateLocal();
    setFieldErrors(localErrors);
    if (Object.keys(localErrors).length > 0) {
      setError(
        new ApiClientError(400, {
          code: "VALIDATION_ERROR",
          message: "Um ou mais campos são inválidos",
          fields: localErrors,
        })
      );
      return;
    }

    setLoading(true);
    try {
      const balance = balanceValue ?? parseBRLInput(balanceMasked) ?? 0;
      await createUser({
        name: name.trim(),
        email: email.trim(),
        document: onlyDigits(document),
        password,
        initialBalance: balance,
      });
      await login(onlyDigits(document), password);
      router.push("/app");
    } catch (err) {
      setError(err);
      if (err instanceof ApiClientError) {
        setFieldErrors(err.fields);
      } else {
        setFieldErrors({});
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="relative min-h-screen bg-[var(--ink)]">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(20,90,85,0.35),transparent_55%)]" />
      <div className="relative z-10 mx-auto flex min-h-screen max-w-md flex-col justify-center px-6 py-12">
        <Link
          href="/"
          className="mb-10 font-[family-name:var(--font-display)] text-2xl text-[var(--foam)]"
        >
          Financial Hub
        </Link>
        <h1 className="font-[family-name:var(--font-display)] text-4xl text-[var(--foam)]">
          Criar conta
        </h1>
        <p className="mt-2 text-sm text-white/55">
          Cadastro com saldo inicial. CPF (11 dígitos) ou CNPJ (14 dígitos).
        </p>
        <form onSubmit={onSubmit} className="mt-8 space-y-5" noValidate>
          <Field label="Nome" error={fieldErrors.name}>
            <input
              className={fieldErrors.name ? inputErrorClass : inputClass}
              required
              minLength={2}
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setFieldErrors((prev) => {
                  const next = { ...prev };
                  delete next.name;
                  return next;
                });
              }}
            />
          </Field>
          <Field label="E-mail" error={fieldErrors.email}>
            <input
              className={fieldErrors.email ? inputErrorClass : inputClass}
              type="email"
              required
              value={email}
              onChange={(e) => {
                setEmail(e.target.value);
                setFieldErrors((prev) => {
                  const next = { ...prev };
                  delete next.email;
                  return next;
                });
              }}
            />
          </Field>
          <Field label="CPF / CNPJ" error={fieldErrors.document}>
            <input
              className={fieldErrors.document ? inputErrorClass : inputClass}
              required
              inputMode="numeric"
              maxLength={18}
              placeholder="52998224725"
              value={document}
              onChange={(e) => {
                setDocument(e.target.value);
                setFieldErrors((prev) => {
                  const next = { ...prev };
                  delete next.document;
                  return next;
                });
              }}
              aria-invalid={Boolean(fieldErrors.document)}
            />
          </Field>
          <Field label="Senha" error={fieldErrors.password}>
            <input
              className={fieldErrors.password ? inputErrorClass : inputClass}
              type="password"
              required
              minLength={6}
              value={password}
              onChange={(e) => {
                setPassword(e.target.value);
                setFieldErrors((prev) => {
                  const next = { ...prev };
                  delete next.password;
                  return next;
                });
              }}
            />
          </Field>
          <Field label="Saldo inicial" error={fieldErrors.initialBalance}>
            <MoneyInput
              error={Boolean(fieldErrors.initialBalance)}
              value={balanceMasked}
              placeholder="0,00"
              min={0}
              onChange={(masked, numeric) => {
                setBalanceMasked(masked);
                setBalanceValue(numeric);
                setFieldErrors((prev) => {
                  const next = { ...prev };
                  delete next.initialBalance;
                  return next;
                });
              }}
            />
          </Field>
          <FormError error={error} onDismiss={() => setError(null)} />
          <div className="flex flex-wrap gap-3 pt-2">
            <button type="submit" disabled={loading} className={buttonPrimaryClass}>
              {loading ? "Criando…" : "Criar conta"}
            </button>
            <Link href="/login" className={buttonGhostClass}>
              Já tenho conta
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
}
